### ISSUE TITLE
Something like --update-all but without installing any packages

### ISSUE THREAD

**Issue by terrisgit** [peterbe/hashin#100]
I'm trying to create a requirements-lock.txt file containing exact versions of all dependencies with hashes so that I can later use "pip install -r requirements-lock.txt" to install the exact version of everything while verifying that the packages haven't been tampered with.

I also don't want hashin and its dependencies to end up in requirements-lock.txt

 Here is how to get what I want via shell scripting. First you start with a pristine Python environment. Then...

```
pip install
pip freeze > requirements-lock.txt
pip install hashin  # Do this after pip freeze !
# Remove my package from requirements-lock.txt (the one installed via setup.py)
grep -v my_package_name requirements-lock.txt > requirements-lock2.txt
# Clear requirements-lock.txt
echo > requirements-lock.txt
# Send every line in requirements-lock2.txt to hashin
tr '\n' ' ' < requirements-lock2.txt | xargs python3 -m hashin -r requirements-lock.txt
rm requirements-lock2.txt
```

**Comment by peterbe** [comment]
My point is if your project is important enough that you need hashes, you should probably be more deliberate and careful with your requirements files. If the project is not important enough to be "organized" with your requirements files, perhaps it's not important enough to use hashes. After all, it's a tool for people who have big projects with high-security standards who are worried about accidentally running with different versions compared to what they tested/developed with.

**Comment by terrisgit** [comment]
My project has a requirements.txt that allows patches to be installed. Freeze is used after upgrading packages and running tests, an infrequent process (once a quarter). We use only requirements-freeze.txt (containing hashes) to do installs. Our project is an internal application rather than a reusable package.

**Comment by peterbe** [comment]
I'm sorry I derailed the issue. Just thought I'd take a moment to share some thoughts on a topic I've thought a lot about. 

Anyway, I think your bash script is fine. The only thing that is weird is that I think it would be cooler if you could do something like this:

```bash
$ pip freeze | grep -v my_package_name | grep -v hashin | xargs python -m hashin -r requirements-lock.txt
```

I.e. that independent of what or how you do it, hashin should be able to read in a list from stdin. 

Is that something you'd be interested in working on?

**Comment by terrisgit** [comment]
hashin has dependencies that I don't want mixed in.

I actually have 5 requirements files for 'dev', 'test', .. It really eventually becomes a mess.

I was pretending in my original post that I used setup.py to install requirements. I'm suspecting that pyenv will eventually replace that.

Your first suggestion is probably better.

1. Install Pristine Python environment plus hashin
2. hash -r requirements.txt

Too bad most newbies will never figure this all out. Maybe someone could publish a modern python3 skeleton project someday.

**Comment by peterbe** [comment]
For what it's worth, and sorry if you already knew this, but a lot of people have `hashin` installed with [pipsi](https://github.com/mitsuhiko/pipsi). That way they can have executable python scripts for their whole machine without "polluting" the virtualenvs.

**Comment by terrisgit** [comment]
No, I had no idea. Thank you. Again, NodeJS is also a cyberattacker's delight. Dependency management is a mess and a huge waste of money.
