### ISSUE TITLE
Ability to install multiple things

### ISSUE THREAD

**Issue by peterbe** [peterbe/hashin#11]
At the moment you have to do:
```
$ hashin myfirstpackage
$ hashin myotherpackage
```
Considering that you can do `pip install myfirstpackage myotherpackage` on one line, `hashin` should support this too.

**Comment by peterbe** [comment]
Actually, this is a bad idea. If you type `hashin package1 package2` then it's going to confuse `package2` with the name of the requirements file. And if you, today, type `hashin package1 package2 package3` it assumes `package2` is the requirements file and `package3` is the algorithm.

**Comment by uolot** [comment]
How about adding a switch to allow installation of multiple packages, like this:
`hashin --list package1,package2 reqs.txt`


Or the other way -- a switch to specify requirements file:
`hashin pkg1 pkg2 -r req.txt`
Assuming that if there's no switch, the format is `hashin <PKG> <REQS>`

**Comment by peterbe** [comment]
Yeah, it'd be doable. In hindsight it was probably a mistake to let the name of the requirements file and the algorithm be positional arguments. I think it'd be more worth spending time trying to understand how to fold this into pip itself.

**Comment by uolot** [comment]
There's already a kind of similar, maybe it will give you some hints: https://github.com/abhiomkar/pip-save
