### ISSUE TITLE
Order of hashes from `get_package_hashes`

### ISSUE THREAD

**Issue by pcorpet** [peterbe/hashin#126]
As in #105 , I wonder if we could expect the output of `get_package_hashes` to have hashes in lexicographical order.

GitHub's dependabot is relying on that and is creating commits in my repo that are conflicting with other tools. Of course dependabot could fix it, but I believe it would be cleaner to have the same order out of `get_package_hashes` than the one done by `run_packages`.

**Comment by peterbe** [comment]
@MarkusH or @pcorpet it would be wonderful to see a PR to attempt this.
