### ISSUE TITLE
Therapist is dead, migrate to pre-commit?

### ISSUE THREAD

**Issue by hartwork** [peterbe/hashin#161]
Based on https://pypi.org/project/therapist/#history I believe that the therapist project is dead?

If so, [pre-commit](https://pre-commit.com/) covers the current therapist use case and more, and is alive.

Here's a demo of existing use of pre-commit in CI in the Python project that powers https://wnpp.debian.net/:
- https://github.com/hartwork/wnpp.debian.net/blob/master/.pre-commit-config.yaml
- https://github.com/hartwork/wnpp.debian.net/blob/master/.github/workflows/pre_commit_run.yml
- https://github.com/hartwork/wnpp.debian.net/blob/master/.github/workflows/pre_commit_detect_outdated.yml

Let's get pull request #159 merged first, though.

**Comment by hartwork** [comment]
@peterbe what do you think?

**Comment by peterbe** [comment]
Yes! Let's use pre-commit instead. If you have a PR I'll review it.

**Comment by hartwork** [comment]
@peterbe deal, expect a pull request before Monday 22nd.

**Comment by hartwork** [comment]
> Yes! Let's use pre-commit instead. If you have a PR I'll review it.

@peterbe ready: #167 :pray:
