### ISSUE TITLE
take a frozen requirements.txt as input (eg from pip-compile)

### ISSUE THREAD

**Issue by graingert** [peterbe/hashin#18]

**Comment by graingert** [comment]
@peterbe I don't get notified about emoji reactions.

**Comment by jezdez** [comment]
This may be not needed anymore if and when https://github.com/nvie/pip-tools/pull/383 is merged

**Comment by Changaco** [comment]
I used something like `sed -r 's/#.*$//' requirements.txt | xargs hashin -r requirements.txt --python-version 2.7` to work around the lack of builtin support for adding hashes to an existing requirements file.

**Comment by danpalmer** [comment]
@jezdez this is still required as the `pip-tools` implementation is platform specific (as it works through `pip`) and therefore hashes 'generated' on, for example, a Mac, cannot be used when installing dependencies on Linux.

**Comment by graingert** [comment]
@jezdez agreed, closing in favour of https://github.com/jazzband/pip-tools/issues/414#issuecomment-288720745

@danpalmer probably worth making a PR that uses hashin in pip-tools?
