### ISSUE TITLE
Running hashin with Python versions >= 3.10 raises PackageError('No releases can be found....')

### ISSUE THREAD

**Issue by vishnuwazoku** [peterbe/hashin#184]
The issue seems to stem from this piece of code.

```python
def expand_python_version(version):
    if not re.match(r"^\d\.\d$", version):
        return [version]
```

The above regular expression assumes the minor version number can have only a single digit. Therefore the result will be incorrect for Python versions >= 3.10.

We probably want to change it to

```python
    if not re.match(r"^\d\.\d*\d$", version)
```

**Comment by hartwork** [comment]
For a reproducer:

```Dockerfile
FROM python:3.10
RUN pip3 install hashin \
        && \
    touch requirements.txt \
        && \
    hashin -r requirements.txt -p 3.10 hashin
```

It takes:
- a) calling function `expand_python_version` from third party Python code or
- b) use of argument `-p PYTHON_VERSION` on the command line
