### ISSUE TITLE
Weird results with `django==1.10`

### ISSUE THREAD

**Issue by rehandalal** [peterbe/hashin#26]
When I run:
```
$ hashin django==1.10 requirements.txt
```
My requirements file gets all crazy (see: https://gist.github.com/rehandalal/5c9289ca0d8f054c16418596950f1cb2).

I've realized this does not happen when I run:
```
$ hashin Django==1.10 requirements.txt
```
Seems to be related to the case not matching.

**Comment by peterbe** [comment]
It could be that the problem only existed in older versions of hashin. Can you reproduce it again? And does it go away after you do `pip install -U hashin`.

**Comment by rehandalal** [comment]
Thanks @peterbe! It's fixed now. It doesn't update `Django`'s hashes, it creates a second entry for `django`, however it doesn't blow up the whole file anymore.

Would be awesome if it would ignore case and update the appropriate entry.

**Comment by peterbe** [comment]
Let's work on https://github.com/peterbe/hashin/issues/27 instead.

**Comment by rehandalal** [comment]
👍🏼
