### ISSUE TITLE
What is the latest version really?

### ISSUE THREAD

**Issue by peterbe** [peterbe/hashin#37]
If I run `hashin Django` it, at the time of writing, installs `Django==1.11rc1` when before I had `Django==1.10.5` installed. 

However, before I did this I ran `piprot -o` and it said 
```
Django (1.10.5) is 55 days out of date. Latest is 1.10.6
```
How does piprot do that and is that the more correct way?

**Comment by peterbe** [comment]
[Here's how piprot does it](https://github.com/sesh/piprot/blob/2b192ad2b2b265f1b9ffa96e4981dd3f4087a6fa/piprot/piprot.py#L71)

**Comment by peterbe** [comment]
Hey @sesh what do you think? Should I copy the `is_prerelease` functionality into hashin? My gut tells me that if someone types `hashin somelib` without specifying version, we probably want the latest non-pre-release version. 
Also, I see in piprot that you do check for [`stable_version`](https://github.com/sesh/piprot/blob/2b192ad2b2b265f1b9ffa96e4981dd3f4087a6fa/piprot/piprot.py#L193) which I didn't even know was a thing. 

Do you think it's a good idea if I copy that PiprotVersion class into hashin?

**Comment by peterbe** [comment]
@mythmon What do you think? Should hashin follow the idea that piprot does?

**Comment by sesh** [comment]
@peterbe I'd look at how `pip` itself does it :)

I don't have stats on it (though it would be pretty easy to check) but I'm pretty sure that `stable_version` is completely under/mis-used by smaller packages on PyPI, so I wouldn't rely on that.

That `is_prerelease` check is pretty naive but also seems to have worked quite well. I haven't had anyone complain about it. I've seen other implementation where any alpha [a-zA-Z] character flags something as pre-release.

Again - if I was doing a big review of `piprot` (which I'm not, it's almost in abandoned/stable state now) I'd probably get a dump of data from PyPI and test these assumptions. The biggest thing I've learned from that project is that people so _crazy things_ with their version numbering.

**Comment by peterbe** [comment]
> I'd look at how pip itself does it :)
Why didn't I think of that?! Only problem is that the code base is larger so I won't be able to do it this afternoon :)

**Comment by mythmon** [comment]
I agree with @sesh: I think that checking `stable_release` likely won't work as well as we'd like. I think the naive `is_prerelease` check would probably work well, but we'd need a way to override it. If I explictly say `hashin foo=2.1beta`, it will install the beta version, right?

Pip probably does six different kinds of black magic to figure it out. I'd say the simpler way is probably better, until we run into problems (Though I'd be curious what pip actually does.)

**Comment by peterbe** [comment]
> [...] it will install the beta version, right?

The code I'm referring to is where hashin figures out *which* version if you deliberately didn't specify one. 

Yes, pip does intimidates me and although I'm confident I can pull it off, doing that will require more time investment and then it might never happen honestly. 

I've used `piprot` for a looong time and never been stumped by its ability to figure out what the latest version probably is.

**Comment by peterbe** [comment]
By the way @mythmon, what piprot does is both. If the `stable_version` key is there, great, if not loop over all the versions, sorted and skipping pre-releases.

**Comment by peterbe** [comment]
See https://github.com/peterbe/hashin/pull/38

**Comment by peterbe** [comment]
https://github.com/peterbe/hashin/pull/38 is merged and released. Just forgot to put the `fixes #37` in the commit message.
